base: 'https://todolist.ddev.site/'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
routes: {  }

imports:
  - { resource: "EXT:t3api/Configuration/Routing/config.yaml" }
